apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-cart-backend
  template:
    metadata:
      labels:
        app: shopping-cart-backend
    spec:
      containers:
      - name: shopping-cart-backend
        image: kartike2001/shopping-cart-backend
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "postgresql://root:password@postgres:5432/shopping_cart"
