apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-backend
spec:
  type: NodePort
  selector:
    app: shopping-cart-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
